hmcts/div-fees-and-payments-service

build.gradle
FPS-Build-Pipeline
* Hardware:
* JDK:
=> DIV2640-FPS-Build-Pipeline

infrastructure/saat.tfvars, infrastructure/sandbox.tfvars, infrastructure/sprod.tfvars
Fix wrong port on test env urls
=> Fixed saat wrong port for tactical test env

build.gradle
=> Removed sonar.host url

build.gradle, infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/prod.tfvars, src/main/java/uk/gov/hmcts/reform/divorce/feepayment/controller/FeePaymentServiceController.java, src/main/java/uk/gov/hmcts/reform/divorce/feepayment/model/Fee.java, src/main/java/uk/gov/hmcts/reform/divorce/feepayment/service/impl/FeePaymentServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/feepayment/service/FeePaymentServiceTest.java, src/test/resources/fee.json
Adds all the changes required for Solicitors PBA.
=> [PREVIEW] Solicitor pba update

Jenkinsfile_parameterized
=> changes resource name

infrastructure/saat.tfvars
=> update fees url for saat

build.gradle, src/main/java/uk/gov/hmcts/reform/divorce/feepayment/controller/helper/RestResponseEntityExceptionHandler.java, src/main/java/uk/gov/hmcts/reform/divorce/feepayment/service/impl/FeePaymentServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/feepayment/controller/FeePaymentServiceControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/feepayment/controller/helper/RestResponseEntityExceptionHandlerUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/feepayment/health/DefaultHttpEntityFactoryUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/feepayment/health/WebServiceHealthCheckUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/feepayment/service/FeePaymentServiceTest.java
Upgrade Spring Boot Version - improving sonar test coverage and added health check unit test
DIV-3048
Review sonar coverage for div-fees-and-payments service & add health check
[DIV-3048](https://tools.hmcts.net/jira/browse/DIV-3048)
* Hardware:
* JDK:
=> [PREVIEW] DIV-3048 - Sonar Test Coverage and Health Check

infrastructure/main.tf
=> [PREVIEW] remove vault provider

Dockerfile, Jenkinsfile_CNP, src/.lint.yml, src/kubernetes/config.aat.yaml, src/kubernetes/deployment.template.yaml
=> enable docker and deploy to kube

src/kubernetes/deployment.template.yaml
=> prepare for aks ingress

Dockerfile, Jenkinsfile_CNP, src/.lint.yml, src/kubernetes/config.aat.yaml, src/kubernetes/deployment.template.yaml
=> Keep Demo up to Date

src/main/java/uk/gov/hmcts/reform/divorce/feepayment/service/impl/FeePaymentServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/feepayment/service/FeePaymentServiceTest.java
=> updated fee changes replacing blank to null

dependency-check-suppressions.xml
=> Sync with master

dependency-check-suppressions.xml
The latest slf4j only has a beta version released with the 'fix', looks like lots of changes in it
=> Suppress slf4j dependency check

dependency-check-suppressions.xml
=> [PREVIEW] DIV-3814 - removed dependency check suppression for CVE-2018-8088

build.gradle, dependency-check-suppressions.xml
Ticket: https://tools.hmcts.net/jira/browse/DIV-4018
Subtask 6: https://tools.hmcts.net/jira/browse/DIV-4024
Updated the owasp.dependencycheck task, a few dependencies in build.gradle and the dependency-check-suppressions.xml file
=> DIV-4018 suppressed dependencies update

Dockerfile, src/test/java/uk/gov/hmcts/reform/divorce/feepayment/insights/AppInsightsTest.java
Added missing test
* Hardware:
* JDK:
=> Added missing test

Jenkinsfile_nightly, README.md, build.gradle, security.sh
=> set up divorce fps security scan

build.gradle
=> Fix tomcat CVE

build.gradle, checkstyle.xml, src/main/java/uk/gov/hmcts/reform/divorce/feepayment/health/DefaultHttpEntityFactory.java, src/main/java/uk/gov/hmcts/reform/divorce/feepayment/health/WebServiceHealthCheck.java, src/test/java/uk/gov/hmcts/reform/divorce/feepayment/controller/FeePaymentServiceControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/feepayment/health/DefaultHttpEntityFactoryUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/feepayment/health/WebServiceHealthCheckUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/feepayment/service/FeePaymentServiceTest.java
- OWASP upgraded to v5, fixed arising vulnerabilities in swagger
- Checkstyle upgraded to 8.21 with an accompanying modification to the `checkstyle.xml` file
- Added checkstyle plugin to build script
Fixes # [DIV-5060](https://tools.hmcts.net/jira/browse/DIV-5060)
=> DIV-5060: OWASP upgrade and checkstyle added to build

build.gradle, checkstyle.xml, src/main/java/uk/gov/hmcts/reform/divorce/feepayment/health/DefaultHttpEntityFactory.java, src/main/java/uk/gov/hmcts/reform/divorce/feepayment/health/WebServiceHealthCheck.java, src/test/java/uk/gov/hmcts/reform/divorce/feepayment/controller/FeePaymentServiceControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/feepayment/health/DefaultHttpEntityFactoryUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/feepayment/health/WebServiceHealthCheckUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/feepayment/service/FeePaymentServiceTest.java
To test the latest changes on Demo
=> Update demo with master - demoupdate

LICENSE.md, README.md
=> DIV-3264: update readmes

build.gradle
fix for CVE-2019-14379, CVE-2019-14439
=> upgradeDataBind

build.gradle
=> upgradeDataBind (#61)

infrastructure/main.tf
Stop using deprecated tf module
- [Y] Bug fix (non-breaking change which fixes an issue)
* Hardware:
* JDK:
=> Use hmcts/cnp module

charts/div-fps/Chart.yaml, charts/div-fps/values.yaml
=> Update placeholder values.yaml for prod

infrastructure/aat.tfvars, infrastructure/prod.tfvars
A revert of some changes in https://github.com/hmcts/div-fees-and-payments-service/pull/71
Fixes pipeline
=> Revert breaking changes to tfvars files. Pipeline still validates those

build.gradle, dependency-check-suppressions.xml, gradle/wrapper/gradle-wrapper.properties, gradlew, gradlew.bat, src/integrationTest/java/uk/gov/hmcts/reform/divorce/feepayment/test/FeePaymentIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/divorce/feepayment/controller/FeePaymentServiceController.java, src/main/java/uk/gov/hmcts/reform/divorce/feepayment/controller/helper/RestResponseEntityExceptionHandler.java, src/main/java/uk/gov/hmcts/reform/divorce/feepayment/management/config/SwaggerConfiguration.java, src/main/java/uk/gov/hmcts/reform/divorce/feepayment/model/Fee.java, src/main/java/uk/gov/hmcts/reform/divorce/feepayment/service/FeePaymentService.java, src/main/java/uk/gov/hmcts/reform/divorce/feepayment/service/impl/FeePaymentServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/feepayment/controller/FeePaymentServiceControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/feepayment/controller/RootControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/feepayment/service/FeePaymentServiceTest.java
- Restructured Gradle dependencies into alphabetical order
- Bumped Gradle wrapper version from 5.6.1 to 5.6.3
- Bumped various dependencies to latest versions & removed 4 now redundant vuln suppressions
- Removed blank lines etc & variable renaming as suggested by PMD
=> Remove vuln suppressions & code cleanup as suggested by PMD

security.sh
https://tools.hmcts.net/confluence/display/RQA/Integrate+with+Glue+for+ignoring+false+postivies
=> Zap security python compatibility

security.sh
add failures to report.json file from ZAP scanner
=> add report json file

.dependabot/config.yml, build.gradle, src/main/java/uk/gov/hmcts/reform/divorce/feepayment/config/HttpConnectionConfiguration.java
=> FIX-Address CVE-2020-5398 and upgrade dependencies + fix deprecated code

Jenkinsfile_CNP, build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RPET-242
* Hardware:
* JDK:
=> RPET-242-remove-deprecated-method

build.gradle
Pipeline failed again due to CVE-2020-9484. Have bumped tomcat version to resolve
=> Infrastructure variables fix

src/main/java/uk/gov/hmcts/reform/divorce/feepayment/service/impl/FeePaymentServiceImpl.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/feepayment/service/FeePaymentServiceTest.java
Payment keyword is being changed from "without-notice" to "GeneralAppWithoutNotice" by the fees and pay. Modifying code to make merging environments in one by one possible.
https://tools.hmcts.net/jira/browse/RPET-222
=> RPET-222: Update payment keyword

src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/RPET-222
Update "without-notice" fee keyword to "GeneralAppWithoutNotice". 
Go live coordinated with FeePay
**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```
=> RPET-222: Update fee keyword

build.gradle
=> Bump up tomcat version

Dockerfile, README.md, build.gradle, checkstyle.xml, lombok.config
Upgrade Java to 11.
[RPET-263](https://tools.hmcts.net/jira/browse/RPET-263)
[RPET-263](https://tools.hmcts.net/jira/browse/RPET-263)
* Hardware:
* JDK:
=> RPET 263: Upgrade java 11

Jenkinsfile_CNP, Jenkinsfile_nightly, audit.json, build.gradle, dependency-check-suppressions.xml, security.sh, src/integrationTest/java/uk/gov/hmcts/reform/divorce/feepayment/test/FeePaymentIntegrationTest.java
Functional Tests has been configured in the nightly pipeline
* Hardware:
* JDK:
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] My changes generate no new warnings
- [ x] Any dependent changes have been merged and published in downstream modules
=> added functional test task to the Nightly Pipeline

build.gradle, dependency-check-suppressions.xml
=> Fixing dependency issues

build.gradle
Solving new dependency vulnerability.
* Hardware:
* JDK:
=> DIV-6688: Solving new dependency vulnerability

build.gradle
=> bump guava and enforce bcprov-jdk15on version

dependency-check-suppressions.xml
http://rse-dashboard.azurewebsites.net/security/
=> Remove outdated supressions

build.gradle, charts/div-fps/Chart.yaml, src/main/resources/application.yml
=> Upgrade base chart to latest version available

build.gradle, dependency-check-suppressions.xml
=> dependencies improvements

build.gradle
=> commonsIo 2.7

charts/div-fps/Chart.yaml
=> RPET-921 bump chart java

Jenkinsfile_CNP, build.gradle, src/contractTest/java/uk/gov/hmcts/reform/divorce/feeandpaymentservice/FeePaymentConsumerTest.java
Fix fee register pact by using number type comparator rather than value
=> Fix fee register pact

build.gradle, charts/div-fps/Chart.yaml
Fix tomcat vulnerabilities by upgrading tomcat embedded jar
DFR-518
- [ x] Bug fix (non-breaking change which fixes an issue)
=> DFR-518: Fix tomcat vulnerabilities

Jenkinsfile_nightly, build.gradle, config/fortify-client.properties, dependency-check-suppressions.xml
Fortify Setup
DFR-466
- [ x] New feature (non-breaking change which adds functionality)
=> Nightly fod scan div fps dfr 466

build.gradle, dependency-check-suppressions.xml, gradle/wrapper/gradle-wrapper.properties, security.sh
DFR-65 - Running functional tests
=> DFR-65 - Fix e2e tests

build.gradle, charts/div-fps/Chart.yaml
=> dependencyFixes

charts/div-fps/Chart.yaml
=> bump java chart

dependency-check-suppressions.xml
=> suppress jackson

charts/div-fps/Chart.yaml, charts/div-fps/values.yaml
https://tools.hmcts.net/jira/browse/DTSSE-1395
=> Autoscaling

charts/div-fps/Chart.yaml, dependency-check-suppressions.xml
=> Suppressing Tomcat embed

src/integrationTest/java/uk/gov/hmcts/reform/divorce/feepayment/test/FeePaymentIntegrationTest.java, src/integrationTest/resources/application.properties
=> Fix Functional tests

Jenkinsfile_nightly, build.gradle, security.sh
=> Fix Nightly pipeline

build.gradle
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[X ] No
```
=> Upgrade SnakeYMl 1.33

dependency-check-suppressions.xml
=> Suppress Jackson databind

audit.json, build.gradle, dependency-check-suppressions.xml
=> Fix dependency issues

Jenkinsfile_CNP, build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DFR-1712
=> DFR-1712 update suppressions

build.gradle, charts/div-fps/Chart.yaml
https://tools.hmcts.net/jira/browse/DFR-1808
=> Dfr 1808 chart update

src/contractTest/java/uk/gov/hmcts/reform/divorce/feeandpaymentservice/FeePaymentConsumerTest.java
Fix fees register pact test
[DFR-2047](https://tools.hmcts.net/jira/browse/DFR-2047)
=> DFR-2047: Fix enforcement fee pact

dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/divorce/feepayment/health/WebServiceHealthCheck.java
Add log for health check to help identify high health check rate across divorce service. 
=> DFR-2637 Add health check log 

infrastructure/state.tf
https://tools.hmcts.net/jira/browse/DFR-3859
Update azurerm provider to v4.32.0
=> DFR-3859: Update azurerm provider to v4.32.0
